version: "3.8"
services:
  flask:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=mongodb
    ports:
      - "8080:8080"
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"