services:
  flask:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=mongodb
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:7
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
