version: "3.8"
services:
  flask:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=mongodb
    ports:
      - "8080:8080"
    healthcheck:
      test: curl -o /dev/null http://localhost:8080 || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
