name: Docker Compose test

# Controls when the workflow will run
on:
  push:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yaml'
      - '.github/workflows/docker-test.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Compose Build & Run
        run: |
          docker compose up -d --build
          sleep 15
      - name: Fetch artifacts
        run: |
          curl -w "\n%{response_code}\n" http://127.0.0.1:8080
          docker-compose logs
      - name: Run Tests
        run: |
          docker compose exec flask pytest tests
          docker compose down
