name: Docker Compose test

# Controls when the workflow will run
on:
  push:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yaml'
      - '.github/workflows/docker-test.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: docker-compose --version

      - name: Run a multi-line script
        run: |
          docker-compose up -d --build
          sleep 30
          curl http://127.0.0.1:8080
          docker-compose down
